Con este bloque de código, definimos distintas variables para chocolate Dubái, pistacho y masa Kataifi. Agrupamos la fuerza de tendencia en tres componentes que forman parte de la tableta de chocolate Dubái. El objetivo es realizar una comparativa de tendencia y fechas respecto a nuestro trabajo previo con las cinco marcas analizadas en el archivo .csv anterior. Se van a generar dos archivos distintos tipo .csv, uno para fuerzas de tendencias semanales y otro mensuales.

In [ ]:
# 1 Se instalan y se cargan las librerías a usar.
!pip install "urllib3<2" pytrends
import pandas as pd
from pytrends.request import TrendReq
import time

pytrends = TrendReq(hl='es-ES', tz=360, retries=10, backoff_factor=2)

# 2 Se crean las variables y se ejecuta la búsqueda.
conceptos = {
   "trend_chocolate_dubai": "Chocolate Dubai + Chocolate de Dubai + Dubai Chocolate + Tableta Dubai",
   "trend_pistacho": "Pistacho + Crema de pistacho + Crema pistacho + Pasta de pistacho",
   "trend_kataifi": "Kataifi + Katayfi + Kadayif + Kadaif + Fideos turcos"
}


all_dfs = []


for nombre_columna, query in conceptos.items():
   try:
       # Se solicitan los datos a Google Trends.
       pytrends.build_payload(
           [query],
           cat=0,
           timeframe='2024-01-01 2026-03-23',
           geo='ES'
       )
       df = pytrends.interest_over_time()


       if not df.empty:
           df = df.drop(columns=['isPartial'], errors='ignore')
           df.columns = [nombre_columna]
           all_dfs.append(df)


       time.sleep(7)


   except Exception as e:
       print(f"❌ Error en {nombre_columna}: {e}")


# 3 Se unen los datos y se generan versiones semanal y mensual
if all_dfs:
  df_semanal = pd.concat(all_dfs, axis=1).reset_index()
  df_semanal['date'] = pd.to_datetime(df_semanal['date'])

  df_semanal.to_csv('trends_chocolate_dubai_semanal.csv', index=False)

  df_mensual = df_semanal.set_index('date').resample('MS').mean().reset_index()
  df_mensual = df_mensual[df_mensual['date'] >= '2024-01-01']
  df_mensual.to_csv('trends_chocolate_dubai_mensual.csv', index=False)

  display(df_semanal.head())
  display(df_mensual.head())
else:
   print("No se pudo recolectar información.")

Collecting urllib3<2
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 2.7 MB/s eta 0:00:00
Collecting pytrends
  Downloading pytrends-4.9.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.12/dist-packages (from pytrends) (2.32.4)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.12/dist-packages (from pytrends) (2.2.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pytrends) (6.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25->pytrends) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0->pytrends) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25->pytrends) (1.17.0)
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 10.0 MB/s eta 0:00:00
Downloading pytrends-4.9.2-py3-none-any.whl (15 kB)
Installing collected packages: urllib3, pytrends
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blobfile 3.2.0 requires urllib3>=2, but you have urllib3 1.26.20 which is incompatible.
Successfully installed pytrends-4.9.2 urllib3-1.26.20

        date  trend_chocolate_dubai  trend_pistacho  trend_kataifi
0 2023-12-31                      0              38              6
1 2024-01-07                      0              36              0
2 2024-01-14                      0              34              0
3 2024-01-21                      0              35              0
4 2024-01-28                      0              40              0

        date  trend_chocolate_dubai  trend_pistacho  trend_kataifi
1 2024-01-01                    0.0           36.25           0.00
2 2024-02-01                    0.0           45.25           3.75
3 2024-03-01                    0.0           44.80           8.60
4 2024-04-01                    0.0           47.50           8.00
5 2024-05-01                    0.0           49.75          15.25